### PR TITLE
added cli-config for making doctrine console tools work

### PR DESCRIPTION
**Pull request by remi-san**
To do that, had to boot the kernel without context (removed the abstract notion of the kernel)

### CODE REVIEW

**Comment by SelrahcD** [comment]
Isn't it weird to have a php file in the config ?

**Comment by qpautrat** [comment]
I don't understand what is this for ?

**Comment by remi-san** [comment]
It's for using the doctrine executable to perform tasks such as generating the proxies for prod performance reasons, etc. This executable requires a cli-config.php file (where the EM has been retrieved).

@SelrahcD I won't reply to your troll

**Comment by jjsaunier** [comment]
Create a new entry point of the application with another kernel than CLI
kernel to doing CLI stuff seems wrong. From a performance POV you can
disable these commands in prod env. BTW doctrine console runner has nothing
related to the application configuration

**Comment by qpautrat** [comment]
Moreover are you sure to have doctrine related commands ?

**Comment by remi-san** [comment]
Fact is, doctrine provides a CLI app (installed in vendor/bin) requiring this config file (either in the root directory or config directory).

This CLI app is very useful as it can generate a lot of stuff before code is deployed in prod (such as generating proxy, cache, etc), and frankly, we cannot deploy MS integrating doctrine ORM without it.

I dont want to boot another CLI app (booting the CLI kernel is pretty useless), but it should be possible.

**Comment by qpautrat** [comment]
Ok i red doctrine documentation about this.
It is really strange imo. But i'm ok.

**Comment by SelrahcD** [comment]
I wasn't trolling. I don't get why a php file containing logic is in the config dir.

**Comment by qpautrat** [comment]
@SelrahcD [doctrine binary wants it](https://github.com/doctrine/doctrine2/blob/e8acfb5891c092da3cedb4536464d2dae852be3b/bin/doctrine.php#L33). Dunno why.
[doc](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/configuration.html#setting-up-the-commandline-tool)

**Comment by SelrahcD** [comment]
ôÔ

**Comment by remi-san** [comment]
If that's really bothering you, I can move it to the root directory, but those are my only two options

**Comment by SelrahcD** [comment]
I don't really care. It just looks strange.

**Comment by SelrahcD** [comment]
This is not required if not in CLI mode though ?

**Comment by remi-san** [comment]
No, it's only required to use the doctrine CLI app which is provided when retrieving doctrine. But as you have to use it to generate proxies and cache before putting it in production, you have to configure it...

But yeah, not the best idea ever...

**Comment by remi-san** [comment]
Ok, so I've used the CliKernel instead of making the root kernel instanciable

**Comment by remi-san** [comment]
Super strange, works fine here... I'll check it with you.

**Pull request merged**
