### PR TITLE
fix symfony/yaml >= 3.0

### PR DESCRIPTION
**Pull request by AlexDpy**
There is a bug in igorw/config-service-provider with the symfony/yaml >= 3.0.

There is a PR to fix it, it's not merged yet so we need to fix it here.
https://github.com/igorw/ConfigServiceProvider/pull/46

### CODE REVIEW

**Comment by SelrahcD** [comment]
Nop. Not a bug.

https://github.com/igorw/ConfigServiceProvider/issues/51

**Comment by remi-san** [comment]
Yes, but the version in composer is in ~2.1.

So, no need to do that in the skeleton.

Feel free to update both yaml and config in composer.json when everything is fixed though.

**Comment by AlexDpy** [comment]
And what if I want to use symfony/yaml 3.0 now without waiting for this to be fixed ?

**Comment by SelrahcD** [comment]
Does the other use of the symfony/yaml requires 3.\* or is it possible to use a 2+ version ?

**Comment by AlexDpy** [comment]
https://github.com/symfony/yaml/blob/2.8/Yaml.php#L36

passing a filename is deprecated since 2.2. I think passing the file_get_contents is the right way to do it anyway.

**Comment by SelrahcD** [comment]
A lot of libs allow to use both v2 and v3. If nothing requires to upgrade to v3 we are not in trouble so far.

**Comment by remi-san** [comment]
And if you really want to upgrade to yaml v3 before config is compatible, create the class you wanted to put in the skeleton in your own project.

**Comment by SelrahcD** [comment]
Won't be possible because symfony/yaml is specified to be ~2.1 here.

Edit : My bad, because we clone the skeleton this is doable.

**Pull request closed without merging**
