### PR TITLE
RFC remove white space concat

### PR DESCRIPTION
**Pull request by jjsaunier**
What do you think, @kurlzor proposed that

### CODE REVIEW

**Comment by ghost** [comment]
if you want... not a big fan of it. really prefer the withespace

**Comment by jjsaunier** [comment]
i'm +0 on this honestly

**Comment by regisbelson** [comment]
The symfony standard is no space, and it doesn't make the code any less readable IMO.

**Comment by regisbelson** [comment]
@SelrahcD ?

**Comment by SelrahcD** [comment]
I'm a strong supporter of the no space syntax.

**Comment by qpautrat** [comment]
I'm a strong supporter of the space syntax.

**Comment by jjsaunier** [comment]
**I'm strong.**

**Pull request closed without merging**
