### PR TITLE
extract doctrine mapping into method & fix short array

### PR DESCRIPTION
**Pull request by jjsaunier**

### CODE REVIEW

**Comment by ghost** [comment]
ok, good for me, if someone else reviews it, i merge it right away

**Comment by regisbelson** [comment]
You might want to change the method prefix to something else than _register_ since you're not supposed to register anything inside. Otherwise :+1: .

**Comment by ghost** [comment]
Yep, I agree with @kurlzor, maybe a `getDoctrineMapping` method would be better

**Comment by jjsaunier** [comment]
@kurlzor @remi-san It's ok to merge now ?

**Comment by remi-san** [comment]
Yep, good for me

**Pull request merged**
